### ISSUE TITLE
The site is asking me to log in

### ISSUE THREAD

**Issue by tweetoruser** [Heinrich-XIAO/Tweetor#162]
It asks me to give a username and password. why is this happening? can you fix to make it bypass?

**Comment by oblivikun** [comment]
This intended behavior, i enabled username and password auth in pythonanywhere to temporarily lock down tweetor for only trusted peoples so you dont delete all the flits and until we figure out how you got the admin account

**Comment by oblivikun** [comment]
Can you give us some insight on how you got the admin account,  make sure you can reproduce the issue locally

**Comment by oblivikun** [comment]
It might be a good idea to make allowed characters a whitelist

**Comment by tweetoruser** [comment]
> It might be a good idea to make allowed characters a whitelist

good idea, i didn't think about that

**Comment by tweetoruser** [comment]
i've added an allowed characters feature.
But anyway I will close this issue since all problems should be resolved now.

**Comment by oblivikun** [comment]
Tweetor should be back up now

**Comment by tweetoruser** [comment]
> Tweetor should be back up now

check tweetor lol
