### ISSUE TITLE
Better spam whatever

### ISSUE THREAD

**Issue by oblivikun** [Heinrich-XIAO/Tweetor#166]
Probably something to check if the previous four posts come from the same ip, even though this could easily be circumvented, it could also prevent monologues and prompt longer flits

**Comment by tweetoruser** [comment]
good idea, you should also check if the last 4 flits are from the same account.

**Comment by tweetoruser** [comment]
but obviously then spammers could use a proxy/vpn and just sign up for a new account

**Comment by tweetoruser** [comment]
but i think it will reduce the amount of spam on the platform.

**Comment by oblivikun** [comment]
Ok will get to work on it tommorow

**Comment by oblivikun** [comment]
done
