### ISSUE TITLE
Make it look good

### ISSUE THREAD

**Issue by oblivikun** [Heinrich-XIAO/Tweetor#169]
Hi! has a few suggestions:
-  Round submit flit box
- Move meme button to bottom left inside flit box
- change the text of the "flit" button under the box to "submit flit" and make it as wide as the box
- Display badges next to username in user page instead of under
- Make leaderboard centered and bigger, also add online indicators to leaderboard
- Add some kind of footer with information and links to rules, tos, privacy policy ...

**Comment by Heinrich-XIAO** [comment]
First three done.

**Comment by Heinrich-XIAO** [comment]
The leaderboard done.

**Comment by Heinrich-XIAO** [comment]
You can do the last one.

**Comment by Heinrich-XIAO** [comment]
And the badge one.

**Comment by Heinrich-XIAO** [comment]
Nvm ill do the badge one
