### ISSUE TITLE
Going back to the top

### ISSUE THREAD

**Issue by Heinrich-XIAO** [Heinrich-XIAO/Tweetor#30]
When trying to make a flit, you might not know what to write, but when you scroll for a while, an idea might come to you, but after scrolling down and you have to scroll up to type your flit, and excessively scrolling is bad as the name suggests. This is why we should have an up arrow that we can click on that shows when ```window.pageYOffset``` is greater than 2000 that resets it by doing ```window.scroll(0,0)```.

**Comment by githublunar** [comment]
I have an HTML/CSS combo for a back to top button.

Will link file. 
[Button.txt](https://github.com/Heinrich-XIAO/Tweetor/files/12403734/Button.txt)

**Comment by Heinrich-XIAO** [comment]
Did you test it on your computer 💻?

**Comment by IscreamforIcecream** [comment]
Not saying this as an offensive thing but who is githublunar? Are they Ria or ?

**Comment by Heinrich-XIAO** [comment]
githublunar is someone we also might hire and give a staff badge to
