### ISSUE TITLE
Profile Pagination

### ISSUE THREAD

**Issue by Heinrich-XIAO** [Heinrich-XIAO/Tweetor#475]

**Comment by Heinrich-XIAO** [comment]
Profile flits have no pagination, therefore they are very slow

**Comment by oblivikun** [comment]
It also causes lots of requests to origin because there is no rate limiting to how fast it gets the flits

**Comment by oblivikun** [comment]
this should be pretty easy

**Comment by oblivikun** [comment]
oops that commit was stupid

**Comment by oblivikun** [comment]
Done in #477

**Comment by Heinrich-XIAO** [comment]
Why did you just merge it without permission. im changing  the security on main

**Comment by Heinrich-XIAO** [comment]
You also should've closed this.
