### ISSUE TITLE
Optimize leaderboard

### ISSUE THREAD

**Issue by Heinrich-XIAO** [Heinrich-XIAO/Tweetor#478]
The leaderboard is not optimized as it takes a getflit with a limit of 1000 which is very slow on slow networks. THis also may break whe nthere were toom any flits.

**Comment by oblivikun** [comment]
Yea this is silly, ill come up with something

**Comment by Heinrich-XIAO** [comment]
Also, dont just make a pr and merge it ur self. i need to check it for stupid vulnerabilities.

**Comment by Heinrich-XIAO** [comment]
Come up with a solution and suggest it to me. done just start working on it before you know its not stupd=id.

**Comment by Heinrich-XIAO** [comment]
assign me to review as well after making the pr

**Comment by oblivikun** [comment]
Ok idea is to calculate leaderboard server side

**Comment by Heinrich-XIAO** [comment]
sure. remember to do caching.

**Comment by Heinrich-XIAO** [comment]
do it all on 478-optimize-leaderboard

**Comment by oblivikun** [comment]
this is hard

**Comment by oblivikun** [comment]
oh come on

**Comment by oblivikun** [comment]
i did it but then messed up with git

**Comment by oblivikun** [comment]
now its gone

**Comment by oblivikun** [comment]
bruh

**Comment by oblivikun** [comment]
i was just looking at the wrong branch
