### ISSUE TITLE
Pagination for DMs

### ISSUE THREAD

**Issue by oblivikun** [Heinrich-XIAO/Tweetor#479]
We should add pagination for the direct messages too, and remove the profanity page because it isnt needed.
when i say we i mean you because this sounds hard

**Comment by Heinrich-XIAO** [comment]
Sure, also use the asignees thing so that i get some notification or just ping me.

**Comment by Heinrich-XIAO** [comment]
removing the profanity page is too complicated

**Comment by Heinrich-XIAO** [comment]
actually nevermind, you can do this one. ill do the other issue from hi
